#define OP_MODE_ECB					0x00
#define OP_MODE_CBC					0x04
#define ALG_CIPHER_DES				0x10
#define ALG_CIPHER_3DES				0x20
#define ALG_CIPHER_AES_128			0x30
#define ALG_CIPHER_AES_192			0x31
#define ALG_CIPHER_AES_256			0x32
#define ALG_CIPHER_PAYA2			0x40
#define ALG_CIPHER_RSA				0x50

#define ALG_CIPHER_DES_ECB			(ALG_CIPHER_DES | OP_MODE_ECB)
#define ALG_CIPHER_DES_CBC			(ALG_CIPHER_DES | OP_MODE_CBC)
#define ALG_CIPHER_3DES_ECB			(ALG_CIPHER_3DES | OP_MODE_ECB)
#define ALG_CIPHER_3DES_CBC			(ALG_CIPHER_3DES | OP_MODE_CBC)
#define ALG_CIPHER_AES_128_ECB		(ALG_CIPHER_AES_128 | OP_MODE_ECB)
#define ALG_CIPHER_AES_128_CBC		(ALG_CIPHER_AES_128 | OP_MODE_CBC)
#define ALG_CIPHER_AES_192_ECB		(ALG_CIPHER_AES_192 | OP_MODE_ECB)
#define ALG_CIPHER_AES_192_CBC		(ALG_CIPHER_AES_192 | OP_MODE_CBC)
#define ALG_CIPHER_AES_256_ECB		(ALG_CIPHER_AES_256 | OP_MODE_ECB)
#define ALG_CIPHER_AES_256_CBC		(ALG_CIPHER_AES_256 | OP_MODE_CBC)
#define ALG_CIPHER_PAYA2_ECB		(ALG_CIPHER_PAYA2 | OP_MODE_ECB)
#define ALG_CIPHER_PAYA2_CBC		(ALG_CIPHER_PAYA2 | OP_MODE_CBC)
#define ALG_HMAC_SHA1				0x80
#define ALG_HMAC_MD5				0x90
#define ALG_HMAC_SHA256				0xA0
#define ALG_HASH_SHA1				0xF0
#define ALG_HASH_SHA256				0xF1
#define ALG_HASH_MD5				0xE0





